name: Codecov

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  codecov:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive ACCEPT_EULA=Y apt-get install -y curl zip unzip tar libssl-dev libcurl4-openssl-dev libunwind-dev git cmake ninja-build gdb protobuf-compiler libsodium-dev libgflags-dev libprotobuf-dev libutempter-dev g++ lcov libtool libtool-bin autoconf

          echo "Host localhost\n  Port 2222\n\n" >> ~/.ssh/config

          sudo /usr/sbin/sshd -p 2222

          ssh-keygen -t rsa -f ~/.ssh/id_rsa -P "" -N ""
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/known_hosts
          ssh -vvvvvvv -o "StrictHostKeyChecking no" -o 'PreferredAuthentications=publickey' localhost "echo foobar" # Fails if we can't ssh into localhost without a password
          if [[ -z "${ACT}" ]]; then auth_header="$(git config --local --get http.https://github.com/.extraheader)"; fi

          git submodule sync --recursive
          git submodule update --init --force --recursive

      # Restore both vcpkg and its artifacts from the GitHub cache service.
      - name: Restore vcpkg and its artifacts.
        uses: actions/cache@v5
        with:
          # The first path is where vcpkg generates artifacts while consuming the vcpkg.json manifest file.
          # The second path is the location of vcpkg (it contains the vcpkg executable and data files).
          # The other paths starting with '!' are exclusions: they contain temporary files generated during the build of the installed packages.
          path: |
            ${{ env.CMAKE_BUILD_DIR }}/vcpkg_installed/
            ${{ env.VCPKG_ROOT }}
            !${{ env.VCPKG_ROOT }}/buildtrees
            !${{ env.VCPKG_ROOT }}/packages
            !${{ env.VCPKG_ROOT }}/downloads
          # The key is composed in a way that it gets properly invalidated: this must happen whenever vcpkg's Git commit id changes, or the list of packages changes. In this case a cache miss must happen and a new entry with a new key with be pushed to GitHub the cache service.
          # The key includes: hash of the vcpkg.json file, the hash of the vcpkg Git commit id, and the used vcpkg's triplet. The vcpkg's commit id would suffice, but computing an hash out it does not harm.
          # Note: given a key, the cache content is immutable. If a cache entry has been created improperly, in order the recreate the right content the key must be changed as well, and it must be brand new (i.e. not existing already).
          key: |
            et-vcpkg-${{ hashFiles( 'vcpkg.json' ) }}-${{ hashFiles( '.git/modules/external/vcpkg/HEAD' )}}-linux-codecov-1

      - name: Build
        run: |
          mkdir build
          pushd build
          cmake -DDISABLE_TELEMETRY=ON -DCODE_COVERAGE=ON ../
          make -j`nproc`
          popd

      - name: Build Test with code coverage
        run: |
          ./build/et-test
          ./test/system_tests/connect_with_jumphost.sh
          lcov --capture --directory . --output-file ./filtered.info
          lcov --remove ./code-coverage.info \
              '/usr/include/*' \
              '/home/*/miniconda3/*' \
              '*/vcpkg_installed/*' \
              '*/external/*' \
              '*/test/integration_tests/*' \
              '*/test/unit_tests/*' \
              '*/test/*' \
              '*/proto/*' \
              '*/cov_build/ET.pb*' \
              '*/cov_build/ETerminal.pb*' \
              --output-file ./filtered.info -rc lcov_branch_coverage=1
          lcov --list ./filtered.info # debug info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./
          fail_ci_if_error: true
          files: ./filtered.info
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
